mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include("userProfile.urls", namespace="UserProfile")),
    path('comments/', include("comments.urls", namespace="Comments")),
    path('', include("products.urls", namespace="Products")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *

app_name="products"

urlpatterns = [
    path("" , index ,name="index" ),
    path("products/product<int:productId>" , productDetails ,name="productDetails" ),
    path("products/actionFromProduct<int:productId>" , action ,name="productAction"),
    path("accounts/cart" , cart ,name="cart" ),
    path("accounts/wishes" , wishes ,name="wishes" ),
    path("accounts/myProducts" , myProducts ,name="myProducts" ),
    path("products/addProduct" , addProduct ,name="addProduct" ),
    path("products/add" , add ,name="add"),

]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

#Funcions
def uploadTo(instance, filename):
    fileName, ext = filename.split(".")
    return ( f"Products/{str(instance.category)}/{str(instance.publisher)}/{str(instance.name)}/{str(instance.name)}.{ext}" )

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Category_detail", kwargs={"pk": self.pk})

class Unit(models.Model):
    """Model definition for Unit."""
    # TODO: Define fields here
    name = models.CharField(max_length=50)

    class Meta:
        """Meta definition for Unit."""
        verbose_name = 'Unit'
        verbose_name_plural = 'Units'

    def __str__(self):
        """Unicode representation of Unit."""
        return self.name


class Product(models.Model):
    order_key = models.IntegerField(unique=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.FloatField(default=0)
    sale = models.FloatField(default=0)
    quantity = models.FloatField(default=0)
    sold = models.FloatField(default=0)
    unit = models.ForeignKey("Unit", on_delete=models.CASCADE, related_name='unit',default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category',default=0)
    rate = models.FloatField(default=0)
    raters = models.ManyToManyField(User, blank=True)
    publisher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='publisher')
    publishedAt = models.DateField(default=timezone.now )
    image = models.ImageField(upload_to=uploadTo, default="/Products/default.jpg")

    class Meta:
        verbose_name = ("Product")
        verbose_name_plural = ("Products")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Product_detail", kwargs={"pk": self.pk})

products/views.py
from django.shortcuts import render, redirect
from .models import *
from userProfile.models import *
from comments.models import *
from django.contrib.auth.models import User
from django.contrib import messages
import math
# Create your views here.
def index(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        userProfile = Profile.objects.get(user=user)
        if request.method == "POST":
            product = Product.objects.get(id=request.POST["id"])
            if "love" in request.POST:
                if product in userProfile.wishes.all():
                    userProfile.wishes.remove(product)
                elif not product in userProfile.wishes.all():
                    userProfile.wishes.add(product)
            elif "buy" in request.POST:
                if product in userProfile.cart.all():
                    userProfile.cart.remove(product)
                elif not product in userProfile.cart.all():
                    userProfile.cart.add(product)
        currentUser = Profile.objects.get(user = user)
    else:
        currentUser = None
    products = Product.objects.all()
    if 'search' in request.GET:
        if request.GET['search']:
            if Product.objects.filter(name__icontains=request.GET['search']).exists():
                products = Product.objects.filter(name__icontains=request.GET['search'])
            else:
                products = Product.objects.filter(name__icontains=request.GET['search'])
        else:
            products = Product.objects.all()
    else:
        products = Product.objects.all()
    context = {
        "products": products.order_by("-order_key"),
        "currentUser": currentUser,
    }
    return render(request, "index.html" , context)

def productDetails(request,productId):
    if request.user.is_authenticated:
        product = Product.objects.get(id=productId)
        comments = Comment.objects.filter(product=product)
        print(product.image.url)
        if product.sale:
            price = product.price * ( 100.0 - product.sale )
        else:
            price = 0
        available = product.quantity - product.sold
        if not product.raters.count() == 0:
            rate = product.rate / product.raters.count()
        else:
            rate = 0
        currentUser = Profile.objects.get(user = request.user)
        context = {
            "product": product,
            "price": price,
            "available": available,
            "rate": rate,
            "currentUser": currentUser,
            "productDetail": True,
            "comments":comments
        }
        return render(request,"productDetails.html" , context)
    else:
        return redirect("UserProfile:signin")

def addProduct(request):
    if request.user.is_authenticated:
        currentUser = Profile.objects.get(user = request.user)
        Units = Unit.objects.all()
        Categories = Category.objects.all()
        context = {
            "currentUser": currentUser,
            "Units":Units,
            "Categories": Categories,
        }
        return render(request,"addProduct.html" , context)
    else:
        return redirect("UserProfile:signin")


def cart(request):
    products = None
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        userProfile = Profile.objects.get(user=user)
        if request.method == "POST":
            product = Product.objects.get(id=request.POST["id"])
            if "love" in request.POST:
                if product in userProfile.wishes.all():
                    userProfile.wishes.remove(product)
                elif not product in userProfile.wishes.all():
                    userProfile.wishes.add(product)
            elif "buy" in request.POST:
                if product in userProfile.cart.all():
                    userProfile.cart.remove(product)
                elif not product in userProfile.cart.all():
                    userProfile.cart.add(product)
        currentUser = Profile.objects.get(user = user)
        products = currentUser.cart.all
        context = {
            "product": products.order_by("id"),
            "currentUser": currentUser,
        }
        return render(request,"index.html" , context)
    else:
        return redirect("UserProfile:signin")
def wishes(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        userProfile = Profile.objects.get(user=user)
        if request.method == "POST":
            product = Product.objects.get(id=request.POST["id"])
            if "love" in request.POST:
                if product in userProfile.wishes.all():
                    userProfile.wishes.remove(product)
                elif not product in userProfile.wishes.all():
                    userProfile.wishes.add(product)
            elif "buy" in request.POST:
                if product in userProfile.cart.all():
                    userProfile.cart.remove(product)
                elif not product in userProfile.cart.all():
                    userProfile.cart.add(product)
        currentUser = Profile.objects.get(user = user)
        products = currentUser.wishes.all
        context = {
            "products":products.order_by("-order_key"),
            "currentUser": currentUser,
        }
        return render(request,"index.html" , context)
    else:
        return redirect("UserProfile:signin")

def myProducts(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        currentUser = Profile.objects.get(user = user)
        products = Product.objects.filter(publisher = user)
        context = {
            "products": products.order_by("-order_key"),
            "currentUser": currentUser,
        }
        return render(request,"index.html" , context)
    else:
        return redirect("UserProfile:signin")

def add(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            p=request.POST
            productName = p["productName"]
            price = float(p["price"])
            sale=float(p["sale"])
            unit = Unit.objects.get(id = p["unit"])
            category= Category.objects.get(id = p['category'])
            quantity = float(p["quantity"])
            description = p["description"]
            image = request.FILES.get('id_image') or 'Products/default.jpg'
            pro = Product(
                order_key=int(Product.objects.all().count()) + 10000,
                name=productName,
                price=price,
                quantity=quantity,
                sale=sale,
                unit=unit,
                description=description,
                publisher=request.user,
                category=category,
                image=image
                )
            pro.save()
        return redirect("Products:index")
    else:
        return redirect("UserProfile:signin")

def action(request,productId):
    if request.user.is_authenticated:
        if request.method=='POST':
            p = request.POST
            product=Product.objects.get(id = productId)
            if 'buy' in p:
                pass
            elif 'addToCart' in p:
                if product in userProfile.cart.all():
                    userProfile.cart.remove(product)
                elif not product in userProfile.cart.all():
                    userProfile.cart.add(product)
            elif 'love' in p:
                    if product in userProfile.wishes.all():
                        userProfile.wishes.remove(product)
                    elif not product in userProfile.wishes.all():
                        userProfile.wishes.add(product)
        return redirect('products:productDetails', productId)
    else:
        return redirect("UserProfile:signin")

products/templates/addProduct.html
{% extends "base.html" %} {% load static %} {% block content %}
<style>
   /* input {
        border-radius: 5px;
        text-align: center;
        padding: 7px;
        font-size: 18px;
        width: 230px;
    }*/
    .selectContainer{
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      justify-content: space-evenly;
      align-items: center;
    }
    .selectContainer select{
      width: 80%;
      padding: 5px;
      border-radius: 9px;
      outline: none;
    }
    .showcase-last textarea{
      width:95%;
      margin: auto;
      display: block;
      border-radius: 10px;
      border: 1px solid #ced4da;
      padding: 11px 15px;
    }
    
    .container {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: center;
        justify-content: center;
        align-items: flex-start;
        margin: 40px auto;
        padding: 0 25px;
    }
    
    .productImage {
        height: 400px;
        width: 300px;
        margin: 0 32px 32px;
        box-shadow: 0px 0px 20px 0px #ccc6c6;
    }
    
    .content {
        max-width: calc(1320px - 300px - 120px);
        min-width: 50%;
    }
    
    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }
    
    .form-label-group input {
        height: auto;
        border-radius: 2rem;
    }
    
    .form-label-group>input,
    .form-label-group>label {
        padding: var(--input-padding-y) var(--input-padding-x);
    }
    
    .form-label-group>label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }
    
    .form-label-group input::-webkit-input-placeholder {
        color: transparent;
    }
    
    .form-label-group input:-ms-input-placeholder {
        color: transparent;
    }
    
    .form-label-group input::-ms-input-placeholder {
        color: transparent;
    }
    
    .form-label-group input::-moz-placeholder {
        color: transparent;
    }
    
    .form-label-group input::placeholder {
        color: transparent;
    }
    
    .form-label-group input:not(:placeholder-shown) {
        padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
        padding-bottom: calc(var(--input-padding-y) / 3);
    }
    
    .form-label-group input:not(:placeholder-shown)~label {
        padding-top: calc(var(--input-padding-y) / 3);
        padding-bottom: calc(var(--input-padding-y) / 3);
        font-size: 12px;
        color: #777;
    }
    
    .btn-lg {
        width: 100%;
    }
    /* Fallback for Edge
    -------------------------------------------------- */
    
    @supports (-ms-ime-align: auto) {
        .form-label-group>label {
            display: none;
        }
        .form-label-group input::-ms-input-placeholder {
            color: #777;
        }
    }
    /* Fallback for IE
-------------------------------------------------- */
    
    @media all and (-ms-high-contrast: none),
    (-ms-high-contrast: active) {
        .form-label-group>label {
            display: none;
        }
        .form-label-group input:-ms-input-placeholder {
            color: #777;
        }
    }
    
     :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: .75rem;
    }
</style>
<div class="container">
    <div id="userProfileImage"  class="productImage card-img-top" style="background: url(/media/Products/default.jpg);" onclick="$('#id_image').click()"></div>
    <form  method="POST" action="{%  url 'Products:add' %}" class="content" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-4 showcase" style="width:100%">
            <div class="showcase-rt-top">
                <div class="pull-left shoe-name">
                    <div class="form-label-group">
                        <input type="text" id="inputName" name="productName" class="form-control" placeholder="اسم المنتج" required autofocus>
                        <label for="inputName">اسم المنتج</label>
                    </div>
                </div>
                <hr class="featurette-divider">
                <div class="pull-left shoe-name">
                    <div class="form-label-group">
                        <input type="number" id="inputPrice" name="price" class="form-control" placeholder="السعر" required>
                        <label for="inputPrice">السعر</label>
                    </div>
                     <div class="form-label-group">
                        <input type="number" id="inputSale" name="sale" class="form-control" placeholder="الخصم">
                        <label for="inputSale">الخصم</label>
                    </div>
                </div>
            </div>
            <hr class="featurette-divider">
            <div class="shocase-rt-bot">
                <div class="form-label-group">
                  <input type="number" id="inputQuantity" name="quantity" class="form-control" placeholder="الكمية" required>
                  <label for="inputQuantity">الكمية</label>
                </div>
                <div class="selectContainer">
                  <label for="unit">وحدة القياس:</label>
                  <Select id="unit" name="unit" required>
                    {% for unit in Units %}
                      <option value="{{unit.id}}">{{unit.name}}</option>
                    {% endfor %}
                  </Select>
                </div>
            </div>
            <hr class="featurette-divider">
            <div class="shocase-rt-bot">
                <div class="selectContainer">
                  <label for="category">الفئة:</label>
                  <Select id="category" name="category" required>
                    {% for category in Categories %}
                      <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                  </Select>
                </div>
            </div>
            <hr class="featurette-divider">
            </div>
            <div class="showcase-last ">
                <h3>وصف المنتج: </h3>
                <textarea name="description" rows="20" cols="15"></textarea>
            </div>
            <div class="row">
              <div class=container>
                <input type="submit" class="btn btn-success" value="اضافة المنتج">
              </div>
            </div>
            <div class="row" style="padding: 0 20px; margin-top: 20px; display: none">
              <input type="file" name="id_image" accept="image/*" id="id_image">
            </div>
        </div>
       
    </form>
</div>
</div>
<script src="{% static 'js/img.js' %}"></script>
{% endblock content %}

products/templates/index.html
{% extends "base.html" %} {% load static %} {% block content %}

<div class="container">
    <br><br>

    <div class="row justify-content-center">
        {% for product in products %}

        <form method="post" class="card product mb-4 col-lg-3">
            {% csrf_token %}

            <input type="hidden" name="id" value="{{product.id}}">
            <div style="background: url({{ product.image.url }});" class="productImage card-img-top"></div>
            <div class="card-body">
                <h5 class="card-title" dir="auto">{{product.name}}</h5>
                <p class="card-text description" dir="auto">{{product.description}}</p>
            </div>
            <div class="card-body" style="position: absolute; bottom: 5px;">
                <h6 style="margin-bottom: 10px;">السعر:
                    {{ product.price }}
                    جنيه</h6>

                <div>
                    <a href="{% url 'products:productDetails' product.id %}" class="moreDetails card-link">قراءة المزيد</a> |
                    <button type="submit" name="buy" href="#" class="frmBtn card-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                        <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0z"></path>
                    </svg>
                </button> |
                    <button type="submit" name="love" href="#" class="love frmBtn card-link">
                {% if product in currentUser.wishes.all %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"></path>
                    </svg>
                {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
                    </svg>
                {% endif %}

                </button>
                </div>
            </div>
        </form>
        {% endfor %}

    </div>
</div>


{% endblock content %}

products/templates/productDetails.html
{% extends "base.html" %} {% load static %} {% block content %}
<style>
    input {
        border-radius: 5px;
        text-align: center;
        padding: 7px;
        font-size: 18px;
        width: 230px;
    }
    
    .container {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: center;
        justify-content: center;
        align-items: flex-start;
        margin: 40px auto;
        padding: 0 25px;
    }
    
    .productImage {
        height: 400px;
        width: 300px;
        margin: 0 32px 32px;
        box-shadow: 0px 0px 20px 0px #ccc6c6;
    }
    
    .content {
        max-width: calc(1320px - 300px - 120px);
    }
</style>
<div class="container">
    <!-- <div style="display: flex; justify-content: center;"> -->
    <!-- <div class="img"> -->
    <div style="background: url({{ product.image.url}});" class="productImage card-img-top"></div>
    <!-- </div> -->
    <div class="content">
        <div class="col-md-4 showcase" style="width:100%">
            <div class="showcase-rt-top">
                <div class="pull-left shoe-name">
                    <h3>{{ product.name }}</h3>
                    <p>{{ product.category }}</p>
                    <h3>السعر:
                        <span>{{ product.price }} جنيه</span>
                    </h3>
                </div>
                <div class="pull-left rating-stars">
                </div>
            </div>
            <hr class="featurette-divider">
            <form method="POST"  action="{%  url 'Products:productAction' product.id %}" >
              {% csrf_token %}
              <div class="shocase-rt-bot">
                  <div class="float-qty-chart" style="padding:10px;">
                      <!-- <h5><label for="rate" class="control-label">التقييم: </label>
                          <input type="number" name="rate" id="rate" value="{{ rate }}" min="0" max="100" step="1" style="
                          ">
                      </h5> -->
                      <input type="hidden" name="id" value="{{product.id}}">
                      <h5><label for="quantity" class="control-label">الكمية: </label>
                          <input type="number" name="quantity" id="quantity" min="0" max="{{ available }}" step="1" value="1" style="
                          ">
                      </h5>
                  </div>
                  <div class="card-body ">
                      <button type="submit " name="buy " href="# " class="frmBtn card-link ">شراء الأن</button> |
                      <!-- <a href="{% url 'products:productDetails' product.id %} " class="moreDetails card-link ">شراء الأن</a> | -->
                      <button type="submit " name="addToCart " href="# " class="frmBtn card-link ">
                          <svg xmlns="http://www.w3.org/2000/svg " width="20 " height="20 " fill="currentColor " class="bi bi-cart-plus-fill " viewBox="0 0 16 16 ">
                              <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1
                                      1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0z "></path>
                          </svg>
                          </button> |
                      <button type="submit " name="love " href="# " class="love frmBtn card-link ">
                      {% if product in currentUser.wishes.all %}
                          <svg xmlns="http://www.w3.org/2000/svg " width="20 " height="20 " fill="currentColor " class="bi bi-heart-fill " viewBox="0 0 16 16 ">
                              <path fill-rule="evenodd " d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z "></path>
                          </svg>
                      {% else %}
                          <svg xmlns="http://www.w3.org/2000/svg " width="20 " height="20 " fill="currentColor " class="bi bi-heart " viewBox="0 0 16 16 ">
                              <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8
                                      15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z "></path>
                          </svg>
                      {% endif %}
                      </button>
                  </div>
                  <hr class="featurette-divider">
              </div>
              </form>
            <div class="showcase-last ">
                <h3>وصف المنتج: </h3>
                <p>
                    {{ product.description }}
                </p>
            </div>
        </div>

    </div>
</div>
</div>
{% endblock content %}