mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include("userProfile.urls", namespace="UserProfile")),
    path('comments/', include("comments.urls", namespace="Comments")),
    path('', include("products.urls", namespace="Products")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *

app_name="products"

urlpatterns = [
    path("" , index ,name="index" ),
    path("products/product<int:productId>" , productDetails ,name="productDetails" ),
    path("products/actionFromProduct<int:productId>" , action ,name="productAction"),
    path("accounts/cart" , cart ,name="cart" ),
    path("accounts/wishes" , wishes ,name="wishes" ),
    path("accounts/myProducts" , myProducts ,name="myProducts" ),
    path("products/addProduct" , addProduct ,name="addProduct" ),
    path("products/add" , add ,name="add"),

]

userProfile/urls.py
from django.urls import path
from .views import *


app_name="UserProfile"

urlpatterns = [
    path("profile" , profile ,name="profile" ),
    path("editProfile" , editProfile ,name="editProfile" ),
    path("editValue" , editValue ,name="editValue" ),
    path("signUp" , signUp ,name="signUp" ),
    path("addAccount" , addAccount ,name="addAccount" ),
    path("signin" , signin ,name="signin" ),
    path("logout" , logout ,name ="logout"),
]

userProfile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


#Funcions
def uploadTo(instance, filename):
    fileName, ext = filename.split(".")
    return ( f"Users/{str(instance.user.username)}/{str(instance.user.username)}.{ext}" )


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to=uploadTo, max_length=1000, default="/Users/default.jpg",blank=True,null=True)
    address1 = models.CharField(max_length=50, null=True, blank=True)
    address2 =  models.CharField(max_length=50, null=True, blank=True)
    phoneNumber =  models.CharField(max_length=50, null=True, blank=True)
    createdAt = models.DateTimeField(default=timezone.now ,auto_now=False, auto_now_add=False)
    lastLoging = models.DateTimeField(default=timezone.now ,auto_now=False, auto_now_add=False)
    products = models.ManyToManyField("products.Product", related_name='products', blank=True)
    wishes = models.ManyToManyField("products.Product", related_name='wishes', blank=True)
    cart = models.ManyToManyField("products.Product", related_name='cart', blank=True)

    class Meta:
        verbose_name = ("Profile")
        verbose_name_plural = ("Profiles")

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("Profile_detail", kwargs={"pk": self.pk})

@receiver(post_save, sender=User)
def update_Create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()  
#@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    pass

userProfile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
######################################################

class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phoneNumber','address1','address2','image']

class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password']

userProfile/views.py
from django.shortcuts import render, redirect
from products.models import *
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib import messages
# Create your views here.


def profile(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        currentUser = Profile.objects.get(user=user)
        products = Product.objects.filter(publisher=user)
        context = {
            "products": products.order_by("-order_key"),
            "currentUser": currentUser,
        }
        return render(request, "profile.html", context)
    else:
        return redirect("UserProfile:signin")

def editProfile(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        currentUser = Profile.objects.get(user=user)
        products = Product.objects.filter(publisher=user)

        userForm = UpdateUserForm(instance=request.user)
        profile = Profile.objects.get(user=user)
        profileForm = UpdateProfileForm(instance=profile)

        context = {
            "products": products.order_by("-order_key"),
            "currentUser": currentUser,
            "profileForm": profileForm,
            "userForm": userForm,
        }
        return render(request, "editProfile.html", context)
    else:
        return redirect("UserProfile:signin")



def editValue(request):
    update(request)
    return redirect("/accounts/profile")

def update(request,Update=True):
    if ( not request.user.is_authenticated and not Update )or (request.user.is_authenticated and Update):
        if request.method == "POST":
            if Update:
                user = request.user
            else:
                user = User.objects.get(username=request.POST['username'])  
            
            userForm = UpdateUserForm(request.POST, instance=user)
            profile = Profile.objects.get(user=user)
            print(profile)
            profileForm = UpdateProfileForm(request.POST, request.FILES, instance=profile)

            if userForm.is_valid and profileForm.is_valid:
                userForm.save()
                profileForm.save()
    else:
        return redirect("UserProfile:signin")

def signUp(request):
    userForm = CreateUserForm()
    profileForm = UpdateProfileForm()
    context = {
        "profileForm": profileForm,
        "userForm": userForm,
    }
    return render(request, "signUp.html", context)

def addAccount(request):
    if request.method == "POST":
        post = request.POST
        username= post['username']
        password= post['password']
        first_name= post['first_name']
        last_name= post['last_name']
        if not User.objects.filter(username=username):
            User.objects.create_user(
                username = username,
                password = password,
                first_name = first_name,
                last_name = last_name,
            )
            update(request,False)
    return redirect("/accounts/signin")

def signin(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            post = request.POST
            username = post['username']
            password = post['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth.login(request, user)
                    return redirect("/")
                else:
                    return redirect("/accounts/signin")
            else:
                return redirect("/accounts/signin")
            
        else:
            if request.user.is_authenticated:
                user = User.objects.get(username=request.user)
                currentUser = Profile.objects.get(user=user)
            else:
                currentUser = None
            context = {
                "currentUser": currentUser,
            }
            return render(request, "signin.html", context)
    else:
        return redirect("/")

def logout(request):
    auth.logout(request)
    return redirect("Products:index")

userProfile/templates/editProfile.html
{% extends "base.html" %} {% load static %} {% block content %}
<style type="text/css">
    body {
        color: #1a202c;
        text-align: right;
        background-color: #efefef;
    }
    
    .main-body {
        padding: 15px;
    }
    
    .card {
        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
    }
    
    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0, 0, 0, 0.125);
        border-radius: 0.25rem;
    }
    
    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }
    
    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }
    
    .gutters-sm>.col,
    .gutters-sm>[class*="col-"] {
        padding-right: 8px;
        padding-left: 8px;
    }
    
    .mb-3,
    .my-3 {
        margin-bottom: 1rem !important;
    }
    
    .bg-gray-300 {
        background-color: #e2e8f0;
    }
    
    .h-100 {
        height: 100% !important;
    }
    
    .shadow-none {
        box-shadow: none !important;
    }
    
    body>div>div>div>div.col-md-4.mb-3>div>div>div>div.userProfileImage {
        width: 190px;
        height: 190px;
    }
    
    @media (min-width: 768px) and ( max-width: 992px) {
        body>div>div>div>div.col-md-4.mb-3>div>div>div>div.userProfileImage {
            width: 140px;
            height: 140px;
        }
    }
    
    input,
    .editValue,
    body>div>div>div>div.col-md-8>div.card.mb-3>div>div>div.col-sm-9.text-secondary {
        text-align: center;
        background: none;
        border: none;
        margin: auto;
    }
    
    input,
    .editValue {
        width: 100%;
    }
    
    body>div>div>div>div.col-md-8>div>div>form>div:last-of-type {
        display: none;
    }
</style>

<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <div class="userProfileImage" id="userProfileImage" onclick="$('#id_image').click()" style="background-image:url({{currentUser.image.url}}); width:190px; height:190px;"></div>
                            <div class="mt-3">
                                <h4 class="text-center">
                                    {{currentUser.user.first_name}} {{currentUser.user.last_name}}
                                </h4>
                                <p class="text-secondary mb-1 text-center">
                                    {{currentUser.user.email}}
                                </p>
                                <p class="text-secondary mb-1 text-center">
                                    {{currentUser.user.username}}
                                </p>
                                <p class="text-muted font-size-sm text-center">
                                    {{currentUser.address1}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <form action="{% url 'UserProfile:editValue' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">الاسم الأول:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{userForm.first_name}}
                                    <!-- <input class="editValue" type="text" name="firstName" value="{{currentUser.user.first_name}}"> -->
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">الاسم الثاني:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{userForm.last_name}}
                                    <!-- <input class="editValue" type="text" name="lastName" value="{{currentUser.user.last_name}}"> -->
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">الايميل:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{userForm.email}}
                                    <!-- <input class="editValue" type="text" name="email" value="{{currentUser.user.email}}"> -->
                                </div>
                            </div>
                            <hr />
                            <!-- <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">كلمة المرور:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input class="editValue" type="text" name="password">
                                    {{userForm.password}}
                                </div>
                            </div>
                            <hr /> -->
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">رقم الهاتف:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <!-- <input class="editValue" type="text" name="phoneNumber" value="{{currentUser.phoneNumber}}"> -->
                                    {{profileForm.phoneNumber}}
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">العنوان الأول:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <!-- <input class="editValue" type="text" name="address1" value="{{currentUser.address1}}"> -->
                                    {{profileForm.address1}}
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">العنوان الثاني:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <!-- <input class="editValue" type="text" name="address2" value="{{currentUser.address2}}"> -->
                                    {{profileForm.address2}}
                                </div>
                            </div>
                            <hr />
                            <div class="row" style="padding: 0 20px; margin-top: 20px;">
                                <input type="submit" class="btn btn-success" value="حفظ البيانات">
                            </div>
                            <!-- <input type="file" id="id_image" name="image" onchange="upload()" accept="image/*" style="display: none;"> -->
                            <div class="row" style="padding: 0 20px; margin-top: 20px;">
                                {{profileForm.image}}
                                <!-- <input type="submit" class="btn btn-success" value="حفظ البيانات"> -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script src="{% static 'js/img.js' %}"></script>
{% endblock content %}

userProfile/templates/signUp.html
{% extends "base.html" %} {% load static %} {% block content %}
<style type="text/css">
    body {
        color: #1a202c;
        text-align: right;
        background-color: #efefef;
    }
    
    .main-body {
        padding: 15px;
    }
    
    .card {
        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
    }
    
    body>div>div>div>div.col-md-4.mb-3>div>div>div>div.userProfileImage {
        width: 190px;
        height: 190px;
    }
    
    @media (min-width: 768px) and ( max-width: 992px) {
        body>div>div>div>div.col-md-4.mb-3>div>div>div>div.userProfileImage {
            width: 140px;
            height: 140px;
        }
    }
    
    input,
    .editValue,
    body>div>div>div>div.col-md-8>div.card.mb-3>div>div>div.col-sm-9.text-secondary {
        text-align: center;
        background: none;
        border: none;
        margin: auto;
    }
    
    input,
    .editValue {
        width: 100%;
    }
    
    body>div>div>div>div.col-md-8>div>div>form>div:last-of-type {
        display: none;
    }
    
    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0, 0, 0, 0.125);
        border-radius: 0.25rem;
    }
    
    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }
    
    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }
    
    .gutters-sm>.col,
    .gutters-sm>[class*="col-"] {
        padding-right: 8px;
        padding-left: 8px;
    }
    
    .mb-3,
    .my-3 {
        margin-bottom: 1rem !important;
    }
    
    .bg-gray-300 {
        background-color: #e2e8f0;
    }
    
    .h-100 {
        height: 100% !important;
    }
    
    .shadow-none {
        box-shadow: none !important;
    }
</style>

<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <div class="userProfileImage" id="userProfileImage" onclick="$('#id_image').click()" style="background-image:url({{currentUser.image.url}}); width:190px; height:190px;"></div>
                            <div class="mt-3">
                                <h4 class="text-center">
                                    {{currentUser.user.first_name}} {{currentUser.user.last_name}}
                                </h4>
                                <p class="text-secondary mb-1 text-center">
                                    {{currentUser.user.email}}
                                </p>
                                <p class="text-secondary mb-1 text-center">
                                    {{currentUser.user.username}}
                                </p>
                                <p class="text-muted font-size-sm text-center">
                                    {{currentUser.address1}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <form action="{% url 'UserProfile:addAccount' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">الاسم الأول:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{userForm.first_name}}
                                    <!-- <input class="editValue" type="text" name="firstName" value="{{currentUser.user.first_name}}"> -->
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">الاسم الثاني:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{userForm.last_name}}
                                    <!-- <input class="editValue" type="text" name="lastName" value="{{currentUser.user.last_name}}"> -->
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">اسم المستخدم:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{userForm.username}}
                                    <!-- <input class="editValue" type="text" name="email" value="{{currentUser.user.email}}"> -->
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">الايميل:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{userForm.email}}
                                    <!-- <input class="editValue" type="text" name="email" value="{{currentUser.user.email}}"> -->
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">كلمة المرور:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <!-- <input class="editValue" type="text" name="password"> -->
                                    {{userForm.password}}
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">رقم الهاتف:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <!-- <input class="editValue" type="text" name="phoneNumber" value="{{currentUser.phoneNumber}}"> -->
                                    {{profileForm.phoneNumber}}
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">العنوان الأول:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <!-- <input class="editValue" type="text" name="address1" value="{{currentUser.address1}}"> -->
                                    {{profileForm.address1}}
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">العنوان الثاني:</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <!-- <input class="editValue" type="text" name="address2" value="{{currentUser.address2}}"> -->
                                    {{profileForm.address2}}
                                </div>
                            </div>
                            <hr />
                            <div class="row" style="padding: 0 20px; margin-top: 20px;">
                                <input type="submit" class="btn btn-success" value="حفظ البيانات">
                            </div>
                            <!-- <input type="file" id="id_image" name="image" onchange="upload()" accept="image/*" style="display: none;"> -->
                            <div class="row" style="padding: 0 20px; margin-top: 20px;">
                                {{profileForm.image}}
                                <!-- <input type="submit" class="btn btn-success" value="حفظ البيانات"> -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script src="{% static 'js/img.js' %}"></script>
{% endblock content %}

userProfile/templates/signin.html
{% extends "base.html" %} {% load static %} {% block content %}
<style>
     :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: .75rem;
    }
    
    .card-signin {
        border: 0;
        border-radius: 1rem;
        box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }
    
    .card-signin .card-title {
        margin-bottom: 2rem;
        font-weight: 300;
        font-size: 1.5rem;
    }
    
    .card-signin .card-body {
        padding: 2rem;
    }
    
    .form-signin {
        width: 100%;
    }
    
    .form-signin .btn {
        font-size: 80%;
        border-radius: 5rem;
        letter-spacing: .1rem;
        font-weight: bold;
        padding: 1rem;
        transition: all 0.2s;
    }
    
    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }
    
    .form-label-group input {
        height: auto;
        border-radius: 2rem;
    }
    
    .form-label-group>input,
    .form-label-group>label {
        padding: var(--input-padding-y) var(--input-padding-x);
    }
    
    .form-label-group>label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }
    
    .form-label-group input::-webkit-input-placeholder {
        color: transparent;
    }
    
    .form-label-group input:-ms-input-placeholder {
        color: transparent;
    }
    
    .form-label-group input::-ms-input-placeholder {
        color: transparent;
    }
    
    .form-label-group input::-moz-placeholder {
        color: transparent;
    }
    
    .form-label-group input::placeholder {
        color: transparent;
    }
    
    .form-label-group input:not(:placeholder-shown) {
        padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
        padding-bottom: calc(var(--input-padding-y) / 3);
    }
    
    .form-label-group input:not(:placeholder-shown)~label {
        padding-top: calc(var(--input-padding-y) / 3);
        padding-bottom: calc(var(--input-padding-y) / 3);
        font-size: 12px;
        color: #777;
    }
    
    .btn-lg {
        width: 100%;
    }
    /* Fallback for Edge
    -------------------------------------------------- */
    
    @supports (-ms-ime-align: auto) {
        .form-label-group>label {
            display: none;
        }
        .form-label-group input::-ms-input-placeholder {
            color: #777;
        }
    }
    /* Fallback for IE
-------------------------------------------------- */
    
    @media all and (-ms-high-contrast: none),
    (-ms-high-contrast: active) {
        .form-label-group>label {
            display: none;
        }
        .form-label-group input:-ms-input-placeholder {
            color: #777;
        }
    }
</style>

<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">تسجيل دخول</h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <div class="form-label-group">
                                <input type="text" id="inputEmail" name="username" class="form-control" placeholder="اسم المستخدم" required autofocus>
                                <label for="inputEmail">اسم المستخدم</label>
                            </div>
                            <div class="form-label-group">
                                <input type="password" id="inputPassword" name="password" class="form-control" placeholder="كلمة المرور" required>
                                <label for="inputPassword">كلمة المرور</label>
                            </div>
                            <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">تسجيل دخول</button>
                            <hr width="100%">
                            <a class="btn btn-lg btn-block text-uppercase" style="border:1px solid #ddd" href="{% url 'UserProfile:signUp' %}">إشتراك</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock content %}