mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include("userProfile.urls", namespace="UserProfile")),
    path('comments/', include("comments.urls", namespace="Comments")),
    path('', include("products.urls", namespace="Products")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *

app_name="products"

urlpatterns = [
    path("" , index ,name="index" ),
    path("products/product<int:productId>" , productDetails ,name="productDetails" ),
    path("products/actionFromProduct<int:productId>" , action ,name="productAction"),
    path("accounts/cart" , cart ,name="cart" ),
    path("accounts/wishes" , wishes ,name="wishes" ),
    path("accounts/myProducts" , myProducts ,name="myProducts" ),
    path("products/addProduct" , addProduct ,name="addProduct" ),
    path("products/add" , add ,name="add"),

]

userProfile/urls.py
from django.urls import path
from .views import *


app_name="UserProfile"

urlpatterns = [
    path("profile" , profile ,name="profile" ),
    path("editProfile" , editProfile ,name="editProfile" ),
    path("editValue" , editValue ,name="editValue" ),
    path("signUp" , signUp ,name="signUp" ),
    path("addAccount" , addAccount ,name="addAccount" ),
    path("signin" , signin ,name="signin" ),
    path("logout" , logout ,name ="logout"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ar">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
   

    <title>Mashtul Store</title>
</head>

<body dir="rtl">
    <!--Start Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'Products:index' %}">مشتول ستور</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'Products:index' %}">المنتجات</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">الحساب</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <div class="userProfileImage" style="background-image:url({{ currentUser.image.url }});background-size: contain;background-position: center;"></div>
                            <h6>{{currentUser.user.first_name}} {{currentUser.user.last_name}}</h6>
                            <li>
                                <hr>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'UserProfile:profile' %}">عرض البيانات</a></li>
                            <li><a class="dropdown-item" href="{% url 'UserProfile:editProfile' %}">تعديل البيانات</a></li>
                            <li><a class="dropdown-item" href="{% url 'Products:myProducts' %}">عرض منتجاتي</a></li>
                            <li><a class="dropdown-item" href="{% url 'Products:addProduct' %}">إضافة منتج</a></li>
                            <li><a class="dropdown-item" href="{% url 'products:wishes' %}">الأمنيات <svg class="love" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"></path>
                            </svg></a></li>
                            <li><a class="dropdown-item" href="{% url 'products:cart' %}">سلة المشتريات <svg class="frmBtn" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0z"></path>
                            </svg></a></li>
                            <li>
                                <hr>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'UserProfile:logout' %}">تسجيل الخروج</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">انضم لنا</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'UserProfile:signin' %}">تسجيل الدخول</a></li>
                            <li><a class="dropdown-item" href="{% url 'UserProfile:signUp' %}">انشاء حساب</a></li>
                        </ul>
                    </li>
                    {% endif %}
                    <!--
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                    -->
                    <li class="nav-item">
                        <a class="nav-link" href="#">تواصل معنا</a>
                    </li>
                </ul>
                <form method="GET" class="d-flex" action="{% url 'Products:index' %}">
                    <input class="form-control me-2" type="search" name="search" placeholder="بحث" aria-label="بحث">
                    <button class="btn btn-outline-success" type="submit">بحث</button>
                </form>
            </div>
        </div>
    </nav>
    <!--End Navbar-->
    {% block content %} {% endblock content %}
    <!-- Footer -->
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>

                <!-- Twitter -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-twitter"></i></a>

                <!-- Google -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google"></i></a>

                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-instagram"></i></a>

                <!-- Linkedin -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>

                <!-- Github -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-github"></i></a>
            </section>
            <!-- Section: Social media -->

            <!-- Section: Form -->
            <section class="">
                <form method="GET" class="d-flex" action="{% url 'Products:index' %}">
                    <input class="form-control me-2" type="search" name=search placeholder="بحث" aria-label="بحث">
                    <button class="btn btn-outline-success" type="submit">بحث</button>
                </form>
            </section>
            <!-- Section: Form -->

            <!-- Section: Text -->
   <!-- Section: Text -->
            <!-- <section class="mb-4">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam eum harum corrupti dicta, aliquam sequi voluptate quas.
                </p>
            </section> -->
            <br>
            <!-- Section: Text -->

            <!-- Section: Links -->
            <section class="">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </section>
            <!-- Section: Links -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: #212529!important;border-top: 1px solid #3f4143">
            &copy;2021 Copyright: Ahmed Tarboush
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="{% static 'js/fontawesome.js' %}"></script>
    <script src="{% static 'js\jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js\bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js\popper.min.js' %}"></script>
    <script src="{% static 'js\bootstrap.min.js' %}"></script>

</body>

</html>